---
- name: Reboot a host and wait for it to return
  hosts: kubew
  remote_user: root
  tasks:
    - name: restart machine
      shell: 'sleep 2 && shutdown -r now'
      async: 1
      poll: 0
      ignore_errors: true

    - name: waiting for server to come back
      local_action: wait_for
        host="{{ inventory_hostname }}"
        port=22
        delay=10
        timeout=120
